//! Auto-update: poll a tiny static update manifest instead of the GitHub API
//! (Zed-style). The release workflow regenerates `updates/stable.json` on
//! every `v*` tag; the app fetches it from raw.githubusercontent, compares the
//! semver version, then downloads the platform package from a direct release
//! URL, verifies its SHA-256, replaces the running app and relaunches.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

pub const REPO_OWNER: &str = "csic21";
pub const REPO_NAME: &str = "zstock";

/// Zed-style lightweight update manifest: one tiny JSON, no GitHub API, no
/// rate limits. Generated by the release workflow into `updates/stable.json`
/// on `main` and served statically via raw.githubusercontent.
const UPDATE_MANIFEST_URL: &str =
    "https://raw.githubusercontent.com/csic21/zstock/main/updates/stable.json";
const APP_BUNDLE_NAME: &str = "Stock Analysis.app";
const BINARY_NAME: &str = "stock";

/// UI state of the auto-updater.
#[derive(Debug, Clone, Default)]
pub enum UpdateState {
    #[default]
    Idle,
    Checking,
    Available(UpdateInfo),
    Downloading(String),
    UpToDate,
    Error(String),
}

/// A newer release that can be installed on this platform.
#[derive(Debug, Clone)]
pub struct UpdateInfo {
    pub version: String,
    pub notes: String,
    pub asset_url: String,
    pub release_url: String,
    /// SHA-256 of the platform package, verified before install.
    pub sha256: Option<String>,
}

#[derive(Deserialize)]
struct UpdateManifest {
    version: String,
    #[serde(default)]
    notes: String,
    #[serde(default)]
    release_url: String,
    #[serde(default)]
    platforms: HashMap<String, PlatformAsset>,
}

#[derive(Deserialize)]
struct PlatformAsset {
    url: String,
    #[serde(default)]
    sha256: Option<String>,
}

fn user_agent() -> String {
    format!(
        "stock-updater/{} (+github.com/{}/{})",
        env!("CARGO_PKG_VERSION"),
        REPO_OWNER,
        REPO_NAME
    )
}

fn platform_key() -> &'static str {
    if cfg!(target_os = "macos") && cfg!(target_arch = "aarch64") {
        "macos-arm64"
    } else if cfg!(target_os = "macos") {
        "macos-x64"
    } else if cfg!(target_os = "windows") {
        "windows-x64"
    } else {
        "unsupported"
    }
}

fn parse_version(tag: &str) -> Result<semver::Version, String> {
    semver::Version::parse(tag.trim_start_matches('v'))
        .map_err(|e| format!("版本号解析失败（{tag}）：{e}"))
}

/// Poll the static update manifest. Returns `Some` when a newer version
/// exists for the current platform, `None` when already up to date.
pub fn check_latest() -> Result<Option<UpdateInfo>, String> {
    let resp = ureq::get(UPDATE_MANIFEST_URL)
        .set("User-Agent", &user_agent())
        .call()
        .map_err(|e| format!("检查更新失败：{e}"))?;
    let manifest: UpdateManifest = resp
        .into_json()
        .map_err(|e| format!("解析更新清单失败：{e}"))?;

    let latest = parse_version(&manifest.version)?;
    let current = parse_version(env!("CARGO_PKG_VERSION"))?;
    if latest <= current {
        return Ok(None);
    }

    let key = platform_key();
    let asset = manifest
        .platforms
        .get(key)
        .ok_or_else(|| format!("该版本未提供当前平台安装包（{key}）"))?;

    Ok(Some(UpdateInfo {
        version: latest.to_string(),
        notes: manifest.notes,
        asset_url: asset.url.clone(),
        release_url: if manifest.release_url.is_empty() {
            format!("https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/tag/v{latest}")
        } else {
            manifest.release_url
        },
        sha256: asset.sha256.clone(),
    }))
}

/// Download the platform package, replace the running app and relaunch.
/// On success this process exits.
pub fn download_and_install(info: &UpdateInfo) -> Result<(), String> {
    let work = std::env::temp_dir().join(format!("stock-update-{}", std::process::id()));
    if work.exists() {
        fs::remove_dir_all(&work).map_err(|e| format!("清理临时目录失败：{e}"))?;
    }
    fs::create_dir_all(&work).map_err(|e| format!("创建临时目录失败：{e}"))?;

    let zip_path = work.join("update.zip");
    let resp = ureq::get(&info.asset_url)
        .set("User-Agent", &user_agent())
        .call()
        .map_err(|e| format!("下载更新包失败：{e}"))?;
    let mut reader = resp.into_reader();
    let mut file = fs::File::create(&zip_path).map_err(|e| format!("写入更新包失败：{e}"))?;
    std::io::copy(&mut reader, &mut file).map_err(|e| format!("下载中断：{e}"))?;
    drop(file);

    if let Some(expected) = &info.sha256 {
        verify_sha256(&zip_path, expected)?;
    }

    let extracted = work.join("extracted");
    fs::create_dir_all(&extracted).map_err(|e| format!("创建解压目录失败：{e}"))?;
    let file = fs::File::open(&zip_path).map_err(|e| format!("打开更新包失败：{e}"))?;
    let mut archive = zip::ZipArchive::new(file).map_err(|e| format!("更新包损坏：{e}"))?;
    archive
        .extract(&extracted)
        .map_err(|e| format!("解压更新包失败：{e}"))?;

    #[cfg(target_os = "macos")]
    install_macos(&extracted)?;
    #[cfg(target_os = "windows")]
    install_windows(&extracted)?;
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    return Err("当前平台暂不支持自动更新".to_string());

    Ok(())
}

/// Verify the downloaded archive against the SHA-256 published in the manifest.
fn verify_sha256(path: &Path, expected: &str) -> Result<(), String> {
    use sha2::{Digest, Sha256};

    let data = fs::read(path).map_err(|e| format!("读取更新包失败：{e}"))?;
    let actual: String = Sha256::digest(&data)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    if !actual.eq_ignore_ascii_case(expected.trim()) {
        return Err("更新包校验失败：SHA-256 与发布清单不一致".to_string());
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn install_macos(extracted: &Path) -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;

    if let Some(bundle) = bundle_dir(&exe) {
        // Running inside a .app bundle: swap the whole bundle.
        let new_bundle = extracted.join(APP_BUNDLE_NAME);
        if !new_bundle.is_dir() {
            return Err(format!("更新包中缺少 {APP_BUNDLE_NAME}"));
        }
        let parent = bundle.parent().ok_or_else(|| "应用目录无效".to_string())?;
        let file_name = bundle
            .file_name()
            .ok_or_else(|| "应用目录无效".to_string())?;
        let backup = parent.join(format!("{}.old-update", file_name.to_string_lossy()));

        let _ = fs::remove_dir_all(&backup);
        fs::rename(&bundle, &backup).map_err(|e| format!("无法移动旧应用（目录只读？）：{e}"))?;
        if let Err(e) = fs::rename(&new_bundle, &bundle) {
            // Fallback for cross-volume moves.
            if let Err(copy_err) = copy_dir_all(&new_bundle, &bundle) {
                let _ = fs::rename(&backup, &bundle); // roll back
                return Err(format!("替换应用失败：{e} / {copy_err}"));
            }
        }
        // Re-sign ad-hoc so the bundle stays consistent after the swap.
        let _ = Command::new("codesign")
            .args(["--force", "-s", "-"])
            .arg(&bundle)
            .output();
        let _ = fs::remove_dir_all(&backup);

        Command::new("open")
            .arg(&bundle)
            .spawn()
            .map_err(|e| format!("启动新版本失败：{e}"))?;
    } else {
        // Standalone binary (e.g. `cargo run`): replace in place.
        replace_binary(&exe, &extracted.join(BINARY_NAME))?;
        Command::new(&exe)
            .spawn()
            .map_err(|e| format!("启动新版本失败：{e}"))?;
    }

    // Give the new process a moment to start, then quit.
    std::thread::sleep(std::time::Duration::from_millis(800));
    std::process::exit(0);
}

#[cfg(target_os = "macos")]
fn bundle_dir(exe: &Path) -> Option<PathBuf> {
    exe.ancestors()
        .find(|p| p.extension().map_or(false, |e| e == "app"))
        .map(Path::to_path_buf)
}

#[cfg(target_os = "macos")]
fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &to)?;
        } else if ty.is_symlink() {
            let target = fs::read_link(entry.path())?;
            std::os::unix::fs::symlink(target, &to)?;
        } else {
            fs::copy(entry.path(), &to)?;
        }
    }
    Ok(())
}

#[cfg(target_os = "windows")]
fn install_windows(extracted: &Path) -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;
    let new_exe = find_named_file(extracted, "stock.exe")
        .ok_or_else(|| "更新包中缺少 stock.exe".to_string())?;
    replace_binary(&exe, &new_exe)?;
    Command::new(&exe)
        .spawn()
        .map_err(|e| format!("启动新版本失败：{e}"))?;

    std::thread::sleep(std::time::Duration::from_millis(800));
    std::process::exit(0);
}

/// Replace `current` with `new`, keeping a `.old` copy that is removed when
/// possible (Windows keeps the running image locked, so cleanup may be deferred).
fn replace_binary(current: &Path, new: &Path) -> Result<(), String> {
    let backup = current.with_extension("exe.old");
    let _ = fs::remove_file(&backup);
    fs::rename(current, &backup).map_err(|e| format!("无法重命名当前程序：{e}"))?;
    if let Err(e) = fs::copy(new, current) {
        let _ = fs::rename(&backup, current);
        return Err(format!("写入新程序失败：{e}"));
    }
    let _ = fs::remove_file(&backup);
    Ok(())
}

#[cfg(target_os = "windows")]
fn find_named_file(root: &Path, name: &str) -> Option<PathBuf> {
    fn walk(dir: &Path, name: &str, depth: usize) -> Option<PathBuf> {
        if depth > 4 {
            return None;
        }
        for entry in fs::read_dir(dir).ok()? {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.is_dir() {
                if let Some(found) = walk(&path, name, depth + 1) {
                    return Some(found);
                }
            } else if path.file_name().map_or(false, |f| f == name) {
                return Some(path);
            }
        }
        None
    }
    walk(root, name, 0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_stable_manifest() {
        let json = r#"{
            "version": "0.0.3",
            "notes": "bug fixes",
            "release_url": "https://github.com/csic21/zstock/releases/tag/v0.0.3",
            "platforms": {
                "macos-arm64": {
                    "url": "https://github.com/csic21/zstock/releases/download/v0.0.3/stock-analysis-macos-arm64.zip",
                    "sha256": "abc123"
                }
            }
        }"#;
        let manifest: UpdateManifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.version, "0.0.3");
        assert_eq!(manifest.notes, "bug fixes");
        let asset = manifest.platforms.get("macos-arm64").unwrap();
        assert_eq!(asset.url.ends_with(".zip"), true);
        assert_eq!(asset.sha256.as_deref(), Some("abc123"));
        // A platform missing from the manifest is fine; the client reports it.
        assert!(manifest.platforms.get("windows-x64").is_none());
    }

    #[test]
    fn platform_key_is_one_of_supported() {
        let key = platform_key();
        assert!(matches!(key, "macos-arm64" | "macos-x64" | "windows-x64"));
    }

    #[test]
    fn verifies_sha256() {
        let path = std::env::temp_dir().join(format!("stock-sha-test-{}", std::process::id()));
        fs::write(&path, b"hello").unwrap();
        let good = verify_sha256(
            &path,
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
        );
        let bad = verify_sha256(&path, "deadbeef");
        fs::remove_file(&path).unwrap();
        assert!(good.is_ok());
        assert!(bad.is_err());
    }
}
