//! Auto-update: poll a tiny static update manifest instead of the GitHub API
//! (Zed-style). The release workflow regenerates `updates/stable.json` on
//! every `v*` tag; the app fetches it from raw.githubusercontent, compares the
//! semver version, then downloads the platform package from a direct release
//! URL, verifies its SHA-256, installs it in place and relaunches. On macOS
//! the new .app contents are synced over the installed bundle with rsync
//! (the running process is untouched), with a whole-bundle swap as fallback.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

pub const REPO_OWNER: &str = "csic21";
pub const REPO_NAME: &str = "zstock";

/// Zed-style lightweight update manifest: one tiny JSON, no GitHub API, no
/// rate limits. Generated by the release workflow into `updates/stable.json`
/// on `main`. Sources are tried in order: the canonical GitHub raw URL first,
/// then a CDN fallback for networks where raw.githubusercontent.com is
/// unreliable or intercepted (e.g. mainland China).
const UPDATE_MANIFEST_URLS: &[&str] = &[
    "https://raw.githubusercontent.com/csic21/zstock/main/updates/stable.json",
    "https://cdn.jsdelivr.net/gh/csic21/zstock@main/updates/stable.json",
];
const UPDATE_FETCH_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
#[cfg(target_os = "macos")]
const APP_BUNDLE_NAME: &str = "ZStock.app";
/// Bundle name used before the v0.0.8 rename; still accepted when installing
/// so packages from either naming era can be applied.
#[cfg(target_os = "macos")]
const LEGACY_BUNDLE_NAME: &str = "Stock Analysis.app";
#[cfg(any(target_os = "macos", target_os = "linux"))]
const BINARY_NAME: &str = "stock";

/// UI state of the auto-updater.
#[derive(Debug, Clone, Default)]
pub enum UpdateState {
    #[default]
    Idle,
    Checking,
    Available(UpdateInfo),
    Downloading(String),
    UpToDate,
    Error(String),
}

/// A newer release that can be installed on this platform.
#[derive(Debug, Clone)]
pub struct UpdateInfo {
    pub version: String,
    pub notes: String,
    pub asset_url: String,
    pub release_url: String,
    /// SHA-256 of the platform package, verified before install.
    pub sha256: Option<String>,
}

#[derive(Deserialize)]
struct UpdateManifest {
    version: String,
    #[serde(default)]
    notes: String,
    #[serde(default)]
    release_url: String,
    #[serde(default)]
    platforms: HashMap<String, PlatformAsset>,
}

#[derive(Deserialize)]
struct PlatformAsset {
    url: String,
    #[serde(default)]
    sha256: Option<String>,
}

fn user_agent() -> String {
    format!(
        "zstock-updater/{} (+github.com/{}/{})",
        env!("CARGO_PKG_VERSION"),
        REPO_OWNER,
        REPO_NAME
    )
}

fn platform_key() -> &'static str {
    if cfg!(target_os = "macos") && cfg!(target_arch = "aarch64") {
        "macos-arm64"
    } else if cfg!(target_os = "macos") {
        "macos-x64"
    } else if cfg!(target_os = "windows") {
        "windows-x64"
    } else if cfg!(target_os = "linux") && cfg!(target_arch = "x86_64") {
        "linux-x64"
    } else if cfg!(target_os = "linux") {
        "linux-arm64"
    } else {
        "unsupported"
    }
}

fn parse_version(tag: &str) -> Result<semver::Version, String> {
    semver::Version::parse(tag.trim_start_matches('v'))
        .map_err(|e| format!("版本号解析失败（{tag}）：{e}"))
}

/// Poll the static update manifest. Returns `Some` when a newer version
/// exists for the current platform, `None` when already up to date.
pub fn check_latest() -> Result<Option<UpdateInfo>, String> {
    let agent = ureq::AgentBuilder::new()
        .timeout_connect(UPDATE_FETCH_TIMEOUT)
        .timeout_read(UPDATE_FETCH_TIMEOUT)
        .timeout_write(UPDATE_FETCH_TIMEOUT)
        .build();

    let mut last_err = String::from("没有可用的更新清单源");
    for url in UPDATE_MANIFEST_URLS {
        match fetch_manifest(&agent, url) {
            Ok(manifest) => return evaluate_manifest(manifest),
            Err(e) => last_err = e,
        }
    }
    Err(last_err)
}

fn fetch_manifest(agent: &ureq::Agent, url: &str) -> Result<UpdateManifest, String> {
    let resp = agent
        .get(url)
        .set("User-Agent", &user_agent())
        .call()
        .map_err(|e| format!("检查更新失败（{url}）：{e}"))?;
    resp.into_json()
        .map_err(|e| format!("解析更新清单失败（{url}）：{e}"))
}

fn evaluate_manifest(manifest: UpdateManifest) -> Result<Option<UpdateInfo>, String> {
    let latest = parse_version(&manifest.version)?;
    let current = parse_version(env!("CARGO_PKG_VERSION"))?;
    if latest <= current {
        return Ok(None);
    }

    let key = platform_key();
    let asset = manifest
        .platforms
        .get(key)
        .ok_or_else(|| format!("该版本未提供当前平台安装包（{key}）"))?;

    Ok(Some(UpdateInfo {
        version: latest.to_string(),
        notes: manifest.notes,
        asset_url: asset.url.clone(),
        release_url: if manifest.release_url.is_empty() {
            format!("https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/tag/v{latest}")
        } else {
            manifest.release_url
        },
        sha256: asset.sha256.clone(),
    }))
}

/// Download the platform package, replace the running app and relaunch.
/// On success this process exits.
pub fn download_and_install(info: &UpdateInfo) -> Result<(), String> {
    let work = std::env::temp_dir().join(format!("stock-update-{}", std::process::id()));
    if work.exists() {
        fs::remove_dir_all(&work).map_err(|e| format!("清理临时目录失败：{e}"))?;
    }
    fs::create_dir_all(&work).map_err(|e| format!("创建临时目录失败：{e}"))?;

    let zip_path = work.join("update.zip");
    let resp = ureq::get(&info.asset_url)
        .set("User-Agent", &user_agent())
        .call()
        .map_err(|e| format!("下载更新包失败：{e}"))?;
    let mut reader = resp.into_reader();
    let mut file = fs::File::create(&zip_path).map_err(|e| format!("写入更新包失败：{e}"))?;
    std::io::copy(&mut reader, &mut file).map_err(|e| format!("下载中断：{e}"))?;
    drop(file);

    if let Some(expected) = &info.sha256 {
        verify_sha256(&zip_path, expected)?;
    }

    let extracted = work.join("extracted");
    fs::create_dir_all(&extracted).map_err(|e| format!("创建解压目录失败：{e}"))?;
    let file = fs::File::open(&zip_path).map_err(|e| format!("打开更新包失败：{e}"))?;
    let mut archive = zip::ZipArchive::new(file).map_err(|e| format!("更新包损坏：{e}"))?;
    archive
        .extract(&extracted)
        .map_err(|e| format!("解压更新包失败：{e}"))?;

    #[cfg(target_os = "macos")]
    install_macos(&extracted)?;
    #[cfg(target_os = "windows")]
    install_windows(&extracted)?;
    #[cfg(target_os = "linux")]
    install_linux(&extracted)?;
    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    return Err("当前平台暂不支持自动更新".to_string());

    Ok(())
}

/// Verify the downloaded archive against the SHA-256 published in the manifest.
fn verify_sha256(path: &Path, expected: &str) -> Result<(), String> {
    use sha2::{Digest, Sha256};

    let data = fs::read(path).map_err(|e| format!("读取更新包失败：{e}"))?;
    let actual: String = Sha256::digest(&data)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    if !actual.eq_ignore_ascii_case(expected.trim()) {
        return Err("更新包校验失败：SHA-256 与发布清单不一致".to_string());
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn install_macos(extracted: &Path) -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;

    if let Some(bundle) = bundle_dir(&exe) {
        // Running inside a .app bundle: prefer Zed-style in-place sync with
        // rsync, falling back to a whole-bundle swap if rsync is unavailable
        // or the sync does not leave a valid binary behind.
        let new_bundle = find_new_bundle(extracted)
            .ok_or_else(|| format!("更新包中缺少 {APP_BUNDLE_NAME} 或 {LEGACY_BUNDLE_NAME}"))?;

        if rsync_into(&new_bundle, &bundle).is_ok()
            && bundle
                .join("Contents")
                .join("MacOS")
                .join(BINARY_NAME)
                .is_file()
        {
            // Re-sign ad-hoc so the bundle stays consistent after the sync.
            let _ = Command::new("codesign")
                .args(["--force", "-s", "-"])
                .arg(&bundle)
                .output();
        } else {
            swap_bundle(&bundle, &new_bundle)?;
        }

        Command::new("open")
            .arg(&bundle)
            .spawn()
            .map_err(|e| format!("启动新版本失败：{e}"))?;
    } else {
        // Standalone binary (e.g. `cargo run`): replace in place.
        replace_binary(&exe, &extracted.join(BINARY_NAME), "old")?;
        Command::new(&exe)
            .spawn()
            .map_err(|e| format!("启动新版本失败：{e}"))?;
    }

    // Give the new process a moment to start, then quit.
    std::thread::sleep(std::time::Duration::from_millis(800));
    std::process::exit(0);
}

/// Sync the contents of `src` (a fresh .app bundle) over `dst` (the installed
/// bundle), Zed-style. Works while the app is running because macOS allows
/// open files to be replaced; the running image is unaffected. A trailing
/// slash on the source copies the bundle *contents* into `dst`.
#[cfg(target_os = "macos")]
fn rsync_into(src: &Path, dst: &Path) -> Result<(), String> {
    let mut src_arg = src.as_os_str().to_os_string();
    src_arg.push("/");
    let output = Command::new("rsync")
        .arg("-a")
        // Compare by content, not just size+mtime: two builds can produce a
        // binary with the same size and mtime, which rsync would otherwise
        // skip even though the code changed.
        .arg("--checksum")
        .arg("--delete")
        .arg("--exclude")
        .arg("Icon?")
        .arg(&src_arg)
        .arg(dst)
        .output()
        .map_err(|e| format!("无法运行 rsync（macOS 自带，无需安装）：{e}"))?;
    if output.status.success() {
        Ok(())
    } else {
        Err(String::from_utf8_lossy(&output.stderr).trim().to_string())
    }
}

/// Whole-bundle swap: move the installed bundle aside, put the new one in
/// place, re-sign, then clean up the backup. Kept as a fallback when rsync
/// is unavailable or the sync leaves the bundle in a bad state.
#[cfg(target_os = "macos")]
fn swap_bundle(bundle: &Path, new_bundle: &Path) -> Result<(), String> {
    let parent = bundle.parent().ok_or_else(|| "应用目录无效".to_string())?;
    let file_name = bundle
        .file_name()
        .ok_or_else(|| "应用目录无效".to_string())?;
    let backup = parent.join(format!("{}.old-update", file_name.to_string_lossy()));

    let _ = fs::remove_dir_all(&backup);
    fs::rename(bundle, &backup).map_err(|e| format!("无法移动旧应用（目录只读？）：{e}"))?;
    if let Err(e) = fs::rename(new_bundle, bundle) {
        // Fallback for cross-volume moves.
        if let Err(copy_err) = copy_dir_all(new_bundle, bundle) {
            let _ = fs::rename(&backup, bundle); // roll back
            return Err(format!("替换应用失败：{e} / {copy_err}"));
        }
    }
    // Re-sign ad-hoc so the bundle stays consistent after the swap.
    let _ = Command::new("codesign")
        .args(["--force", "-s", "-"])
        .arg(bundle)
        .output();
    let _ = fs::remove_dir_all(&backup);
    Ok(())
}

#[cfg(target_os = "macos")]
fn bundle_dir(exe: &Path) -> Option<PathBuf> {
    exe.ancestors()
        .find(|p| p.extension().is_some_and(|e| e == "app"))
        .map(Path::to_path_buf)
}

/// Locate the app bundle inside an extracted update, preferring the current
/// bundle name and falling back to the pre-rename one.
#[cfg(target_os = "macos")]
fn find_new_bundle(extracted: &Path) -> Option<PathBuf> {
    let primary = extracted.join(APP_BUNDLE_NAME);
    if primary.is_dir() {
        return Some(primary);
    }
    let legacy = extracted.join(LEGACY_BUNDLE_NAME);
    legacy.is_dir().then_some(legacy)
}

#[cfg(target_os = "macos")]
fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &to)?;
        } else if ty.is_symlink() {
            let target = fs::read_link(entry.path())?;
            std::os::unix::fs::symlink(target, &to)?;
        } else {
            fs::copy(entry.path(), &to)?;
        }
    }
    Ok(())
}

#[cfg(target_os = "windows")]
fn install_windows(extracted: &Path) -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;
    let new_exe = find_named_file(extracted, "stock.exe")
        .ok_or_else(|| "更新包中缺少 stock.exe".to_string())?;
    replace_binary(&exe, &new_exe, "exe.old")?;
    Command::new(&exe)
        .spawn()
        .map_err(|e| format!("启动新版本失败：{e}"))?;

    std::thread::sleep(std::time::Duration::from_millis(800));
    std::process::exit(0);
}

#[cfg(target_os = "linux")]
fn install_linux(extracted: &Path) -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;
    let new_exe = find_named_file(extracted, BINARY_NAME)
        .ok_or_else(|| format!("更新包中缺少 {BINARY_NAME}"))?;
    replace_binary(&exe, &new_exe, "old")?;
    Command::new(&exe)
        .spawn()
        .map_err(|e| format!("启动新版本失败：{e}"))?;

    std::thread::sleep(std::time::Duration::from_millis(800));
    std::process::exit(0);
}

/// Replace `current` with `new`, keeping a `.old` copy that is removed when
/// possible (Windows keeps the running image locked, so cleanup may be deferred).
fn replace_binary(current: &Path, new: &Path, backup_suffix: &str) -> Result<(), String> {
    let backup = current.with_extension(backup_suffix);
    let _ = fs::remove_file(&backup);
    fs::rename(current, &backup).map_err(|e| format!("无法重命名当前程序：{e}"))?;
    if let Err(e) = fs::copy(new, current) {
        let _ = fs::rename(&backup, current);
        return Err(format!("写入新程序失败：{e}"));
    }
    let _ = fs::remove_file(&backup);
    Ok(())
}

#[cfg(any(target_os = "windows", target_os = "linux"))]
fn find_named_file(root: &Path, name: &str) -> Option<PathBuf> {
    fn walk(dir: &Path, name: &str, depth: usize) -> Option<PathBuf> {
        if depth > 4 {
            return None;
        }
        for entry in fs::read_dir(dir).ok()? {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.is_dir() {
                if let Some(found) = walk(&path, name, depth + 1) {
                    return Some(found);
                }
            } else if path.file_name().is_some_and(|f| f == name) {
                return Some(path);
            }
        }
        None
    }
    walk(root, name, 0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_stable_manifest() {
        let json = r#"{
            "version": "0.0.3",
            "notes": "bug fixes",
            "release_url": "https://github.com/csic21/zstock/releases/tag/v0.0.3",
            "platforms": {
                "macos-arm64": {
                    "url": "https://github.com/csic21/zstock/releases/download/v0.0.3/zstock-macos-arm64.zip",
                    "sha256": "abc123"
                }
            }
        }"#;
        let manifest: UpdateManifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.version, "0.0.3");
        assert_eq!(manifest.notes, "bug fixes");
        let asset = manifest.platforms.get("macos-arm64").unwrap();
        assert!(asset.url.ends_with(".zip"));
        assert_eq!(asset.sha256.as_deref(), Some("abc123"));
        // A platform missing from the manifest is fine; the client reports it.
        assert!(!manifest.platforms.contains_key("windows-x64"));
    }

    #[test]
    fn platform_key_is_one_of_supported() {
        let key = platform_key();
        assert!(matches!(
            key,
            "macos-arm64" | "macos-x64" | "windows-x64" | "linux-x64" | "linux-arm64"
        ));
    }

    #[test]
    #[cfg(target_os = "macos")]
    fn finds_new_bundle_preferring_current_name() {
        let dir = std::env::temp_dir().join(format!("stock-bundle-new-{}", std::process::id()));
        fs::create_dir_all(dir.join(APP_BUNDLE_NAME)).unwrap();
        fs::create_dir_all(dir.join(LEGACY_BUNDLE_NAME)).unwrap();
        let found = find_new_bundle(&dir).unwrap();
        assert_eq!(found.file_name().unwrap(), APP_BUNDLE_NAME);
        fs::remove_dir_all(&dir).unwrap();

        let legacy =
            std::env::temp_dir().join(format!("stock-bundle-legacy-{}", std::process::id()));
        fs::create_dir_all(legacy.join(LEGACY_BUNDLE_NAME)).unwrap();
        let found = find_new_bundle(&legacy).unwrap();
        assert_eq!(found.file_name().unwrap(), LEGACY_BUNDLE_NAME);
        fs::remove_dir_all(&legacy).unwrap();
    }

    #[test]
    fn evaluate_manifest_is_up_to_date_when_not_newer() {
        let manifest = UpdateManifest {
            version: env!("CARGO_PKG_VERSION").to_string(),
            notes: String::new(),
            release_url: String::new(),
            platforms: HashMap::new(),
        };
        assert!(evaluate_manifest(manifest).unwrap().is_none());
    }

    #[test]
    fn evaluate_manifest_reports_missing_platform() {
        let manifest = UpdateManifest {
            version: "99.0.0".to_string(),
            notes: String::new(),
            release_url: String::new(),
            platforms: HashMap::new(),
        };
        assert!(evaluate_manifest(manifest).is_err());
    }

    #[test]
    fn verifies_sha256() {
        let path = std::env::temp_dir().join(format!("stock-sha-test-{}", std::process::id()));
        fs::write(&path, b"hello").unwrap();
        let good = verify_sha256(
            &path,
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
        );
        let bad = verify_sha256(&path, "deadbeef");
        fs::remove_file(&path).unwrap();
        assert!(good.is_ok());
        assert!(bad.is_err());
    }
}
