//! Auto-update: verify an independently signed static update manifest before
//! interpreting any release data. The guarded release workflow publishes
//! `updates/stable-v2.json`; the app verifies its embedded-key signature and
//! compares the semver version, then downloads the official platform package,
//! verifies its SHA-256, installs it in place and relaunches. On macOS
//! a complete .app is staged beside the installed bundle before a whole-bundle
//! swap; the previous bundle is retained for recovery.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use base64::Engine;
use serde::Deserialize;
use std::io::Read;

pub const REPO_OWNER: &str = "csic21";
pub const REPO_NAME: &str = "zstock";

/// Lightweight signed update manifest: one tiny JSON, no GitHub API, no
/// rate limits. Generated by the release workflow into `updates/stable-v2.json`
/// on `main`. Sources are tried in order: the canonical GitHub raw URL first,
/// then a CDN fallback for networks where raw.githubusercontent.com is
/// unreliable or intercepted (e.g. mainland China).
const UPDATE_MANIFEST_URLS: &[&str] = &[
    "https://raw.githubusercontent.com/csic21/zstock/main/updates/stable-v2.json",
    "https://cdn.jsdelivr.net/gh/csic21/zstock@main/updates/stable-v2.json",
];
/// Owner-provided release verification key, compiled into the application.
/// Never accept a key from the network manifest or a runtime environment variable.
const UPDATE_PUBLIC_KEY_HEX: &str = include_str!("../updates/signing-public-key.hex");
const SIGNING_CONTEXT: &[u8] = b"zstock-update-v1\n";
const MAX_MANIFEST_BYTES: u64 = 128 * 1024;
const MAX_PACKAGE_BYTES: u64 = 256 * 1024 * 1024;
const MAX_EXTRACTED_BYTES: u64 = 1024 * 1024 * 1024;
const MANUAL_UPDATE: &str =
    "自动更新安全验证不可用，请从 https://github.com/csic21/zstock/releases 手动下载安装";
const UPDATE_FETCH_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);
#[cfg(target_os = "macos")]
const APP_BUNDLE_NAME: &str = "ZStock.app";
/// Bundle name used before the v0.0.8 rename; still accepted when installing
/// so packages from either naming era can be applied.
#[cfg(target_os = "macos")]
const LEGACY_BUNDLE_NAME: &str = "Stock Analysis.app";
#[cfg(any(target_os = "macos", target_os = "linux"))]
const BINARY_NAME: &str = "stock";

/// UI state of the auto-updater.
#[derive(Debug, Clone, Default)]
pub enum UpdateState {
    #[default]
    Idle,
    Checking,
    Available(UpdateInfo),
    Downloading(String),
    UpToDate,
    Error(String),
}

/// A newer release that can be installed on this platform.
#[derive(Debug, Clone)]
pub struct UpdateInfo {
    pub version: String,
    pub notes: String,
    asset_url: String,
    pub release_url: String,
    /// SHA-256 of the platform package, verified before install.
    sha256: String,
}

#[derive(Deserialize)]
struct UpdateManifest {
    version: String,
    #[serde(default)]
    notes: String,
    #[serde(default)]
    release_url: String,
    #[serde(default)]
    platforms: HashMap<String, PlatformAsset>,
}

#[derive(Deserialize)]
struct PlatformAsset {
    url: String,
    sha256: String,
}

fn user_agent() -> String {
    format!(
        "zstock-updater/{} (+github.com/{}/{})",
        env!("CARGO_PKG_VERSION"),
        REPO_OWNER,
        REPO_NAME
    )
}

fn platform_key() -> &'static str {
    if cfg!(target_os = "macos") && cfg!(target_arch = "aarch64") {
        "macos-arm64"
    } else if cfg!(target_os = "macos") {
        "macos-x64"
    } else if cfg!(target_os = "windows") {
        "windows-x64"
    } else if cfg!(target_os = "linux") && cfg!(target_arch = "x86_64") {
        "linux-x64"
    } else if cfg!(target_os = "linux") {
        "linux-arm64"
    } else {
        "unsupported"
    }
}

fn parse_version(tag: &str) -> Result<semver::Version, String> {
    semver::Version::parse(tag.trim_start_matches('v'))
        .map_err(|e| format!("版本号解析失败（{tag}）：{e}"))
}

/// Poll the static update manifest. Returns `Some` when a newer version
/// exists for the current platform, `None` when already up to date.
pub fn check_latest() -> Result<Option<UpdateInfo>, String> {
    let public_key = release_public_key()?;
    let agent = update_agent();

    let mut last_err = String::from("没有可用的更新清单源");
    for url in UPDATE_MANIFEST_URLS {
        match fetch_manifest(&agent, url, &public_key) {
            Ok(manifest) => return evaluate_manifest(manifest),
            Err(e) => last_err = e,
        }
    }
    Err(last_err)
}

fn update_agent() -> ureq::Agent {
    ureq::AgentBuilder::new()
        .timeout_connect(UPDATE_FETCH_TIMEOUT)
        .timeout_read(UPDATE_FETCH_TIMEOUT)
        .timeout_write(UPDATE_FETCH_TIMEOUT)
        .timeout(std::time::Duration::from_secs(120))
        .redirects(0)
        .build()
}

fn decode_hex<const N: usize>(value: &str) -> Result<[u8; N], String> {
    let value = value.trim();
    if value.len() != N * 2 || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err("签名或校验值格式无效".into());
    }
    let mut bytes = [0; N];
    for (index, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&value[index * 2..index * 2 + 2], 16)
            .map_err(|_| "签名或校验值格式无效".to_string())?;
    }
    Ok(bytes)
}

fn release_public_key() -> Result<[u8; 32], String> {
    decode_hex(UPDATE_PUBLIC_KEY_HEX).map_err(|_| MANUAL_UPDATE.to_string())
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct SignedManifest {
    schema: u32,
    /// Exact UTF-8 bytes signed after SIGNING_CONTEXT; no JSON reserialization.
    payload: String,
    signature: String,
}

fn verify_manifest(bytes: &[u8], public_key: &[u8; 32]) -> Result<UpdateManifest, String> {
    if bytes.len() as u64 > MAX_MANIFEST_BYTES {
        return Err("更新清单过大".into());
    }
    let signed: SignedManifest =
        serde_json::from_slice(bytes).map_err(|_| "缺少有效的更新签名；请手动更新".to_string())?;
    if signed.schema != 1 {
        return Err("不支持的更新签名格式".into());
    }
    let signature = base64::engine::general_purpose::STANDARD
        .decode(&signed.signature)
        .map_err(|_| "更新签名格式无效".to_string())?;
    let mut message = Vec::from(SIGNING_CONTEXT);
    message.extend_from_slice(signed.payload.as_bytes());
    ring::signature::UnparsedPublicKey::new(&ring::signature::ED25519, public_key)
        .verify(&message, &signature)
        .map_err(|_| "更新清单签名验证失败；已阻止安装".to_string())?;
    serde_json::from_str(&signed.payload).map_err(|_| "已签名更新清单格式无效".to_string())
}

fn fetch_manifest(
    agent: &ureq::Agent,
    url: &str,
    public_key: &[u8; 32],
) -> Result<UpdateManifest, String> {
    // Manifest endpoints are fixed, HTTPS-only and must not redirect.
    let resp = agent
        .get(url)
        .set("User-Agent", &user_agent())
        .call()
        .map_err(|e| format!("检查更新失败：{e}"))?;
    if resp.status() != 200 {
        return Err("更新清单服务器返回异常状态".into());
    }
    let mut bytes = Vec::new();
    resp.into_reader()
        .take(MAX_MANIFEST_BYTES + 1)
        .read_to_end(&mut bytes)
        .map_err(|e| format!("读取更新清单失败：{e}"))?;
    verify_manifest(&bytes, public_key)
}

fn canonical_release_url(version: &semver::Version) -> String {
    format!("https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/tag/v{version}")
}

fn validate_asset(version: &str, url: &str, hash: &str) -> Result<(), String> {
    let version = parse_version(version)?;
    if !version.pre.is_empty() || !version.build.is_empty() {
        return Err("只允许稳定版本更新".into());
    }
    let expected = format!(
        "https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/download/v{version}/zstock-{}.zip",
        platform_key()
    );
    if url != expected {
        return Err("更新包地址不属于该版本的官方发布".into());
    }
    decode_hex::<32>(hash)?;
    Ok(())
}

/// GitHub release downloads redirect to its asset CDN. No HTTP, credentials,
/// custom ports, arbitrary mirrors or redirects back to repository pages.
fn approved_download_redirect(url: &str) -> bool {
    let Some(rest) = url.strip_prefix("https://release-assets.githubusercontent.com/") else {
        return false;
    };
    !rest.is_empty() && !rest.contains('\\') && !rest.contains('#')
}

fn download_response(agent: &ureq::Agent, initial: &str) -> Result<ureq::Response, String> {
    let mut url = initial.to_string();
    for _ in 0..5 {
        let response = agent
            .get(&url)
            .set("User-Agent", &user_agent())
            .call()
            .map_err(|e| format!("下载更新包失败：{e}"))?;
        if response.status() == 200 {
            return Ok(response);
        }
        if !matches!(response.status(), 301 | 302 | 303 | 307 | 308) {
            return Err("更新下载服务器返回异常状态".into());
        }
        let next = response
            .header("Location")
            .ok_or("更新下载缺少重定向地址")?;
        if !approved_download_redirect(next) {
            return Err("已阻止非官方更新下载重定向".into());
        }
        url = next.to_string();
    }
    Err("更新下载重定向过多".into())
}

fn evaluate_manifest(manifest: UpdateManifest) -> Result<Option<UpdateInfo>, String> {
    let latest = parse_version(&manifest.version)?;
    let current = parse_version(env!("CARGO_PKG_VERSION"))?;
    if latest <= current {
        return Ok(None);
    }

    let key = platform_key();
    let asset = manifest
        .platforms
        .get(key)
        .ok_or_else(|| format!("该版本未提供当前平台安装包（{key}）"))?;

    validate_asset(&latest.to_string(), &asset.url, &asset.sha256)?;
    if manifest.release_url != canonical_release_url(&latest) {
        return Err("发布说明地址不属于官方版本".into());
    }

    Ok(Some(UpdateInfo {
        version: latest.to_string(),
        notes: manifest.notes,
        asset_url: asset.url.clone(),
        release_url: manifest.release_url,
        sha256: asset.sha256.clone(),
    }))
}

/// Install verified bytes. The UI drains durable saves before relaunching/quit.
pub fn download_and_install(info: &UpdateInfo) -> Result<PathBuf, String> {
    release_public_key()?;
    validate_asset(&info.version, &info.asset_url, &info.sha256)?;
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| e.to_string())?
        .as_nanos();
    let work = std::env::temp_dir().join(format!("stock-update-{}-{nonce}", std::process::id()));
    let builder = fs::DirBuilder::new();
    #[cfg(unix)]
    let builder = {
        use std::os::unix::fs::DirBuilderExt;
        let mut builder = builder;
        builder.mode(0o700);
        builder
    };
    builder
        .create(&work)
        .map_err(|e| format!("创建私有临时目录失败：{e}"))?;

    let zip_path = work.join("update.zip");
    let resp = download_response(&update_agent(), &info.asset_url)?;
    let mut reader = resp.into_reader().take(MAX_PACKAGE_BYTES + 1);
    let mut file = fs::File::create(&zip_path).map_err(|e| format!("写入更新包失败：{e}"))?;
    let count = std::io::copy(&mut reader, &mut file).map_err(|e| format!("下载中断：{e}"))?;
    if count > MAX_PACKAGE_BYTES {
        return Err("更新包超出大小限制".into());
    }
    file.sync_all()
        .map_err(|e| format!("保存更新包失败：{e}"))?;
    drop(file);
    verify_sha256(&zip_path, &info.sha256)?;

    let extracted = work.join("extracted");
    fs::create_dir_all(&extracted).map_err(|e| format!("创建解压目录失败：{e}"))?;
    let file = fs::File::open(&zip_path).map_err(|e| format!("打开更新包失败：{e}"))?;
    let mut archive = zip::ZipArchive::new(file).map_err(|e| format!("更新包损坏：{e}"))?;
    let mut extracted_size = 0_u64;
    let archive_entries = archive.len();
    for index in 0..archive_entries {
        let entry = archive.by_index(index).map_err(|e| e.to_string())?;
        if entry.enclosed_name().is_none() || entry.is_symlink() {
            return Err("更新包包含不安全路径".into());
        }
        extracted_size = extracted_size
            .checked_add(entry.size())
            .ok_or("更新包过大")?;
        if extracted_size > MAX_EXTRACTED_BYTES || archive_entries > 10_000 {
            return Err("更新包解压大小超限".into());
        }
    }
    archive
        .extract(&extracted)
        .map_err(|e| format!("解压更新包失败：{e}"))?;

    #[cfg(target_os = "macos")]
    let installed = install_macos(&extracted)?;
    #[cfg(target_os = "windows")]
    let installed = install_windows(&extracted)?;
    #[cfg(target_os = "linux")]
    let installed = install_linux(&extracted)?;
    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    return Err("当前平台暂不支持自动更新".to_string());

    Ok(installed)
}

/// Verify the downloaded archive against the SHA-256 published in the manifest.
fn verify_sha256(path: &Path, expected: &str) -> Result<(), String> {
    use sha2::{Digest, Sha256};

    decode_hex::<32>(expected)?;
    let mut file = fs::File::open(path).map_err(|e| format!("读取更新包失败：{e}"))?;
    let mut digest = Sha256::new();
    std::io::copy(&mut file, &mut digest).map_err(|e| format!("读取更新包失败：{e}"))?;
    let actual: String = digest
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    if !actual.eq_ignore_ascii_case(expected.trim()) {
        return Err("更新包校验失败：SHA-256 与发布清单不一致".to_string());
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn install_macos(extracted: &Path) -> Result<PathBuf, String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;

    if let Some(bundle) = bundle_dir(&exe) {
        // Stage a complete bundle on the destination filesystem before touching
        // the running installation. Never rsync partially over the live bundle.
        let new_bundle = find_new_bundle(extracted)
            .ok_or_else(|| format!("更新包中缺少 {APP_BUNDLE_NAME} 或 {LEGACY_BUNDLE_NAME}"))?;
        swap_bundle(&bundle, &new_bundle)?;
        Ok(bundle)
    } else {
        let new_binary = find_new_bundle(extracted)
            .map(|bundle| bundle.join("Contents/MacOS").join(BINARY_NAME))
            .unwrap_or_else(|| extracted.join(BINARY_NAME));
        replace_binary(&exe, &new_binary, "old")?;
        Ok(exe)
    }
}

/// Stage and swap on one filesystem. The old bundle is retained as a recovery
/// copy; a failed copy never modifies the installed application.
#[cfg(target_os = "macos")]
fn swap_bundle(bundle: &Path, new_bundle: &Path) -> Result<(), String> {
    let parent = bundle.parent().ok_or_else(|| "应用目录无效".to_string())?;
    let file_name = bundle
        .file_name()
        .ok_or_else(|| "应用目录无效".to_string())?
        .to_string_lossy();
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| e.to_string())?
        .as_nanos();
    let staged = parent.join(format!(".{file_name}.new-{nonce}"));
    let backup = parent.join(format!("{file_name}.old-update-{nonce}"));
    fs::create_dir(&staged).map_err(|e| format!("无法准备应用暂存目录：{e}"))?;
    if let Err(error) = copy_dir_all(new_bundle, &staged) {
        let _ = fs::remove_dir_all(&staged);
        return Err(format!("暂存新应用失败，旧应用未修改：{error}"));
    }
    if !staged.join("Contents/MacOS").join(BINARY_NAME).is_file() {
        let _ = fs::remove_dir_all(&staged);
        return Err("新应用缺少可执行文件，旧应用未修改".into());
    }
    fs::rename(bundle, &backup).map_err(|e| format!("无法保留旧应用：{e}"))?;
    if let Err(error) = fs::rename(&staged, bundle) {
        if let Err(rollback) = fs::rename(&backup, bundle) {
            return Err(format!(
                "替换和恢复失败：{error} / {rollback}；旧应用保留在 {}",
                backup.display()
            ));
        }
        return Err(format!("替换应用失败，已恢复旧应用：{error}"));
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn bundle_dir(exe: &Path) -> Option<PathBuf> {
    exe.ancestors()
        .find(|p| p.extension().is_some_and(|e| e == "app"))
        .map(Path::to_path_buf)
}

/// Locate the app bundle inside an extracted update, preferring the current
/// bundle name and falling back to the pre-rename one.
#[cfg(target_os = "macos")]
fn find_new_bundle(extracted: &Path) -> Option<PathBuf> {
    let primary = extracted.join(APP_BUNDLE_NAME);
    if primary.is_dir() {
        return Some(primary);
    }
    let legacy = extracted.join(LEGACY_BUNDLE_NAME);
    legacy.is_dir().then_some(legacy)
}

#[cfg(target_os = "macos")]
fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &to)?;
        } else if ty.is_symlink() {
            let target = fs::read_link(entry.path())?;
            std::os::unix::fs::symlink(target, &to)?;
        } else {
            fs::copy(entry.path(), &to)?;
        }
    }
    Ok(())
}

#[cfg(target_os = "windows")]
fn install_windows(extracted: &Path) -> Result<PathBuf, String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;
    let new_exe = find_named_file(extracted, "stock.exe")
        .ok_or_else(|| "更新包中缺少 stock.exe".to_string())?;
    replace_binary(&exe, &new_exe, "exe.old")?;
    Ok(exe)
}

#[cfg(target_os = "linux")]
fn install_linux(extracted: &Path) -> Result<PathBuf, String> {
    let exe = std::env::current_exe().map_err(|e| format!("定位当前程序失败：{e}"))?;
    let new_exe = find_named_file(extracted, BINARY_NAME)
        .ok_or_else(|| format!("更新包中缺少 {BINARY_NAME}"))?;
    replace_binary(&exe, &new_exe, "old")?;
    Ok(exe)
}

/// Called only after the application has confirmed all accepted writes drained.
pub fn relaunch(installed: &Path) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    if installed
        .extension()
        .is_some_and(|extension| extension == "app")
    {
        Command::new("open")
            .arg("-n")
            .arg(installed)
            .spawn()
            .map_err(|e| format!("启动新版本失败：{e}"))?;
        return Ok(());
    }
    Command::new(installed)
        .spawn()
        .map_err(|e| format!("启动新版本失败：{e}"))?;
    Ok(())
}

/// Replace `current` with `new`, keeping a `.old` copy that is removed when
/// possible (Windows keeps the running image locked, so cleanup may be deferred).
fn replace_binary(current: &Path, new: &Path, backup_suffix: &str) -> Result<(), String> {
    let backup = current.with_extension(backup_suffix);
    let _ = fs::remove_file(&backup);
    fs::rename(current, &backup).map_err(|e| format!("无法重命名当前程序：{e}"))?;
    if let Err(e) = fs::copy(new, current) {
        let _ = fs::rename(&backup, current);
        return Err(format!("写入新程序失败：{e}"));
    }
    let _ = fs::remove_file(&backup);
    Ok(())
}

#[cfg(any(target_os = "windows", target_os = "linux"))]
fn find_named_file(root: &Path, name: &str) -> Option<PathBuf> {
    fn walk(dir: &Path, name: &str, depth: usize) -> Option<PathBuf> {
        if depth > 4 {
            return None;
        }
        for entry in fs::read_dir(dir).ok()? {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.is_dir() {
                if let Some(found) = walk(&path, name, depth + 1) {
                    return Some(found);
                }
            } else if path.file_name().is_some_and(|f| f == name) {
                return Some(path);
            }
        }
        None
    }
    walk(root, name, 0)
}

#[cfg(test)]
pub(crate) fn test_update_info() -> UpdateInfo {
    let key = decode_hex::<32>("d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a")
        .unwrap();
    evaluate_manifest(
        verify_manifest(
            include_bytes!("../tests/fixtures/update-signed-v1.json"),
            &key,
        )
        .unwrap(),
    )
    .unwrap()
    .unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_stable_manifest() {
        let json = r#"{
            "version": "0.0.3",
            "notes": "bug fixes",
            "release_url": "https://github.com/csic21/zstock/releases/tag/v0.0.3",
            "platforms": {
                "macos-arm64": {
                    "url": "https://github.com/csic21/zstock/releases/download/v0.0.3/zstock-macos-arm64.zip",
                    "sha256": "abc123"
                }
            }
        }"#;
        let manifest: UpdateManifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.version, "0.0.3");
        assert_eq!(manifest.notes, "bug fixes");
        let asset = manifest.platforms.get("macos-arm64").unwrap();
        assert!(asset.url.ends_with(".zip"));
        assert_eq!(asset.sha256, "abc123");
        // A platform missing from the manifest is fine; the client reports it.
        assert!(!manifest.platforms.contains_key("windows-x64"));
    }

    #[test]
    fn platform_key_is_one_of_supported() {
        let key = platform_key();
        assert!(matches!(
            key,
            "macos-arm64" | "macos-x64" | "windows-x64" | "linux-x64" | "linux-arm64"
        ));
    }

    #[test]
    #[cfg(target_os = "macos")]
    fn finds_new_bundle_preferring_current_name() {
        let dir = std::env::temp_dir().join(format!("stock-bundle-new-{}", std::process::id()));
        fs::create_dir_all(dir.join(APP_BUNDLE_NAME)).unwrap();
        fs::create_dir_all(dir.join(LEGACY_BUNDLE_NAME)).unwrap();
        let found = find_new_bundle(&dir).unwrap();
        assert_eq!(found.file_name().unwrap(), APP_BUNDLE_NAME);
        fs::remove_dir_all(&dir).unwrap();

        let legacy =
            std::env::temp_dir().join(format!("stock-bundle-legacy-{}", std::process::id()));
        fs::create_dir_all(legacy.join(LEGACY_BUNDLE_NAME)).unwrap();
        let found = find_new_bundle(&legacy).unwrap();
        assert_eq!(found.file_name().unwrap(), LEGACY_BUNDLE_NAME);
        fs::remove_dir_all(&legacy).unwrap();
    }

    #[test]
    fn evaluate_manifest_is_up_to_date_when_not_newer() {
        let manifest = UpdateManifest {
            version: env!("CARGO_PKG_VERSION").to_string(),
            notes: String::new(),
            release_url: String::new(),
            platforms: HashMap::new(),
        };
        assert!(evaluate_manifest(manifest).unwrap().is_none());
    }

    #[test]
    fn evaluate_manifest_reports_missing_platform() {
        let manifest = UpdateManifest {
            version: "99.0.0".to_string(),
            notes: String::new(),
            release_url: String::new(),
            platforms: HashMap::new(),
        };
        assert!(evaluate_manifest(manifest).is_err());
    }

    #[test]
    fn verifies_sha256() {
        let path = std::env::temp_dir().join(format!("stock-sha-test-{}", std::process::id()));
        fs::write(&path, b"hello").unwrap();
        let good = verify_sha256(
            &path,
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
        );
        let bad = verify_sha256(&path, "deadbeef");
        fs::remove_file(&path).unwrap();
        assert!(good.is_ok());
        assert!(bad.is_err());
    }
    #[test]
    fn pinned_signature_verifies_exact_payload_and_rejects_tampering() {
        // Published RFC 8032 verification key, never the production trust root.
        let key =
            decode_hex::<32>("d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a")
                .unwrap();
        let bytes = include_bytes!("../tests/fixtures/update-signed-v1.json");
        let manifest = verify_manifest(bytes, &key).unwrap();
        assert_eq!(manifest.version, "99.0.0");
        assert!(evaluate_manifest(manifest).unwrap().is_some());
        let mut envelope: serde_json::Value = serde_json::from_slice(bytes).unwrap();
        envelope["payload"] = serde_json::Value::String(
            envelope["payload"]
                .as_str()
                .unwrap()
                .replace("99.0.0", "99.0.1"),
        );
        assert!(verify_manifest(&serde_json::to_vec(&envelope).unwrap(), &key).is_err());
        assert!(verify_manifest(bytes, &[0; 32]).is_err());
        assert!(verify_manifest(br#"{"version":"99.0.0","platforms":{}}"#, &key).is_err());
        assert!(decode_hex::<32>("").is_err());
    }

    #[test]
    fn package_hash_and_official_versioned_https_url_are_mandatory() {
        let hash = "a".repeat(64);
        let valid = format!(
            "https://github.com/csic21/zstock/releases/download/v99.0.0/zstock-{}.zip",
            platform_key()
        );
        assert!(validate_asset("99.0.0", &valid, &hash).is_ok());
        for url in [
            valid.replace("https://", "http://"),
            valid.replace("csic21", "attacker"),
            format!("{valid}?redirect=evil"),
            valid.replace("v99.0.0", "v98.0.0"),
        ] {
            assert!(validate_asset("99.0.0", &url, &hash).is_err());
        }
        for hash in ["", "abc", &"x".repeat(64)] {
            assert!(validate_asset("99.0.0", &valid, hash).is_err());
        }
        let value = r#"{"version":"99.0.0","platforms":{"linux-x64":{"url":"https://example.test/update.zip"}}}"#;
        assert!(serde_json::from_str::<UpdateManifest>(value).is_err());
    }

    #[test]
    fn download_redirects_are_restricted_to_github_asset_cdn_https() {
        assert!(approved_download_redirect(
            "https://release-assets.githubusercontent.com/github-production-release-asset/123?token=dummy"
        ));
        for url in [
            "http://release-assets.githubusercontent.com/a",
            "https://release-assets.githubusercontent.com.evil.test/a",
            "https://release-assets.githubusercontent.com@evil.test/a",
            "https://release-assets.githubusercontent.com:443/a",
            "https://evil.test/a",
            "file:///tmp/update.zip",
        ] {
            assert!(!approved_download_redirect(url), "{url}");
        }
    }
}
